### ISSUE TITLE
How did you get xsdk.info to point to these github pages

### ISSUE THREAD

**Issue by markcmiller86** [xsdk-project/xsdk-project.github.io#1]
I notice that the settings do not have a _custom_ domain name set. So, I am wondering how you were able to get `https://xsdk.info` to point to the jekyell generated site for which this repo is the source?

I think part of it *must* have to do with the naming of this project as `<project-name>.github.io`.

I am trying to do something similar from my user (e.g. not organization) github account and have met with limited success. I want to get `kvmesh.org` to point to `https://markcmiller86.github.io/kvmesh/home/` I tried a custom domain and that kinda worked but it seemd to point to a generated site that was not generated correctly and where image links were failing.

**Comment by maherou** [comment]
If I understand the question correctly, this page should help:

https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by markcmiller86** [comment]
Yeah, I've read through all those refs already. Ok, was thinking there was some naming magic I needed but didn't know about.
